services:
  lavshyak.adplatformlocations.webapi:
    image: lavshyak.adplatformlocations.webapi:0.0.2
    build:
      context: .
      dockerfile: AdPlatformLocations.WebApi/Dockerfile
    ports:
      - "6464:80"
    environment:
      - ASPNETCORE_URLS=http://*:80
      - ADD_AND_USE_SWAGGER_AND_OPENAPI=true
  
  lavshyak.adplatformlocations.lib.tests:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    working_dir: /src
    volumes:
      - ./:/src
    command: '
    dotnet test
    '